--- 
- 
  become: true
  hosts: all
  name: "install tomcat"
  tasks: ~
- 
  apt: 
    name: openjdk-8-jdk
    state: present
    update_cache: true
  name: "install java and update packages"
- 
  apt: 
    name: tomcat8
    state: present
  name: "install tomcat"
- 
  get_url: 
    dest: /var/lib/tomcat8/webapps/gameoflife.war
    url: "https://referenceappkhaja.s3-us-west-2.amazonaws.com/gameoflife.war"
  name: "download the file"
     

  
